package xxnvt.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 16 15:41:23 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DbObjectsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DbObjectsVOImpl() {
    }
}
